version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running tests"
      - source venv/bin/activate
      - python manage.py test
  build:
    commands:
      - echo "Build complete"
artifacts:
  files:
    - '**/*'
