version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - . venv/bin/activate
      - python manage.py check

  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'

